server:
  port: 9000
spring:
  application:
    name: "auth-server"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# Path for the cliente and resource server.
client-resource_server:
  port: 9091
  host: http://127.0.0.1:${client-resource_server.port}